### ISSUE TITLE
Upgrade to platform-api

### ISSUE THREAD

**Issue by tmaier** [JustinLove/autoscaler#44]
Heroku-api is deprecated.

Platform-api https://github.com/heroku/platform-api is the new way to go.
This would allow to sign in with oauth and also to limit the scope of autoscaler (https://devcenter.heroku.com/articles/oauth#scopes)

I think this would then also work well together with 2FA https://devcenter.heroku.com/articles/two-factor-authentication and we would not need to store our password in the app config

**Comment by JustinLove** [comment]
Supported on master via HerokuPlatformScaler and HEROKU_ACCESS_TOKEN, at least in so far as unit testing.
