### ISSUE TITLE
time to release a new version?

### ISSUE THREAD

**Issue by siong1987** [JustinLove/autoscaler#47]
the current version in rubygems doesn't seem to support sidekiq 3.  i think it is the right time to upgrade the version on rubygems to the latest?

**Comment by claudiob** [comment]
@JustinLove great job with this project!

I agree that it would be nice to have a new version of the gem on Rubygems.org

What's your opinion on that?

**Comment by devill** [comment]
+1 for new release! It looks a bit like a hack to add the github repo into the Gemfile

**Comment by tmaier** [comment]
@JustinLove: Sidekiq 3 support seems not to be high on your priority list, but it would be really great if you could cut out a new gem for us :)

**Comment by JustinLove** [comment]
CC @bkudria #32 ?

**Comment by warmwaffles** [comment]
Any news on cutting a new release to support sidekiq 3?

**Comment by JustinLove** [comment]
Master is caught up with pull requests and issues I intend to implement. I still don't have an application for this and am relying on unit tests.  Anybody with an application care to smoke test it?

**Comment by claudiob** [comment]
I just tried in production (on Heroku) and it works. If you cut a gem at this version, I'm going to point at it.

Thanks again for your work.
