### ISSUE TITLE
Linear scaling strategy with long running jobs

### ISSUE THREAD

**Issue by skalb** [JustinLove/autoscaler#48]
Say I have 5 dynos with a worker capacity of 5 each performing 1 long running job, the autoscaler will see that I only need 1 server and downscale to 1 server.

This effectively kills the long running job on 4 out 5 dynos (they still get retried, but have to be restarted from scratch).

Is there any way to mitigate this problem?

Ideally, I'd like to only issue downscales if nothing is active or queued even if I end up running my dynos for a bit longer.

**Comment by JustinLove** [comment]
I pretty much counted on SideKiq retries for this, but it may depend on the exact workload.
