### ISSUE TITLE
don't want to use set_initial_workers

### ISSUE THREAD

**Issue by Skeyelab** [JustinLove/autoscaler#63]
I have things working *almost* how I want them, however, I cannot figure out how to do what I have, without using `set_initial_workers`

Here is my initializer, any help would be greatly appreciated:  

```require 'autoscaler/sidekiq'
require 'autoscaler/heroku_platform_scaler'
require 'autoscaler/linear_scaling_strategy'


if ENV['HEROKU_ACCESS_TOKEN'] and ENV['HEROKU_APP']
  Sidekiq.configure_client do |config|
    config.client_middleware do |chain|
      heroku   = Autoscaler::HerokuPlatformScaler.new
      strategy = Autoscaler::DelayedShutdown.new(
        Autoscaler::LinearScalingStrategy.new(ENV['MAX_WORKERS'].to_i, ENV['SIDEKIQ_CONCURRENCY'].to_i),
        10
      )
      Autoscaler::Sidekiq::Client
      .add_to_chain(chain, 'files'=>heroku, 'rows'=>heroku, 'default'=>heroku)
      .set_initial_workers(strategy)
    end
  end

  Sidekiq.configure_server do |config|
    config.server_middleware do |chain|
      strategy = Autoscaler::DelayedShutdown.new(
        Autoscaler::LinearScalingStrategy.new(ENV['MAX_WORKERS'].to_i, ENV['SIDEKIQ_CONCURRENCY'].to_i),
        10
      )
      chain.add(Autoscaler::Sidekiq::Server, Autoscaler::HerokuPlatformScaler.new, strategy)
    end
  end
end```

**Comment by JustinLove** [comment]
What is your use case?

One thing you can do is put strategy (and the scaler) outside the configure blocks.  Server and client will be running different instances, bus you won't have to replicate the code.

**Comment by Skeyelab** [comment]
My app has very little use.  Since heroku cycles the dyno's about once a day, it always sits w one worker waiting after the cycle.  I want to sit w 0 workers.

I'm thinking of making a dummy job that runs once an hour or something that will esentially trigger the autoscaler.

As for your comment about putting the strategy outside the config blocks, can you show me what you mean w the code I provided?

**Comment by JustinLove** [comment]
Initial workers is more for the case where you *want* workers to start when the web app starts, in case there was leftover work.

Otherwise workers might start immediately on a dyno restart if they were running when it shut down, but you can reset that to 0 via herkou UI. In any case, the monitor should shut it down it down after the idle period.

Here is a rough untested reorg to common variables. This is similar to what happens in the code examles; the idea with strategies is similar to use of the common scaler.

```
require 'autoscaler/heroku_platform_scaler'
require 'autoscaler/linear_scaling_strategy'


if ENV['HEROKU_ACCESS_TOKEN'] and ENV['HEROKU_APP']
  heroku   = Autoscaler::HerokuPlatformScaler.new
  strategy = Autoscaler::DelayedShutdown.new(
        Autoscaler::LinearScalingStrategy.new(ENV['MAX_WORKERS'].to_i, ENV['SIDEKIQ_CONCURRENCY'].to_i),
        10
      )
  Sidekiq.configure_client do |config|
    config.client_middleware do |chain| 
      Autoscaler::Sidekiq::Client
      .add_to_chain(chain, 'files'=>heroku, 'rows'=>heroku, 'default'=>heroku)
      .set_initial_workers(strategy)
    end
  end

  Sidekiq.configure_server do |config|
    config.server_middleware do |chain|
      chain.add(Autoscaler::Sidekiq::Server, heroku, strategy)
    end
  end
end
```

**Comment by Skeyelab** [comment]
So for my use case I shod remove `.set_initial_workers(strategy)`?

**Comment by JustinLove** [comment]
Sounds like it

The basic pattern is a low traffic app with no workers running; when a job gets queued, a worker is started, and then shuts down when the queue is idle. Were you seeing something different?
