### ISSUE TITLE
Sidekiq 5 support?

### ISSUE THREAD

**Issue by shadowed87** [JustinLove/autoscaler#64]
Does this gem support sidekiq 5?

Bundler could not find compatible versions for gem "sidekiq":
  In snapshot (Gemfile.lock):
    sidekiq (= 5.0.0)
  In Gemfile:
    sidekiq
  autoscaler was resolved to 0.12.0, which depends on
      sidekiq (~> 4.0)

**Comment by JustinLove** [comment]
New branch sidekiq5 with updated version spec. Fixed issue with new method in redis gem 3.3, tests pass. Anyone care to test before I push to rubygems?

**Comment by JustinLove** [comment]
0.13 published for Sidekiq 5
