### ISSUE TITLE
Heroku platform API error

### ISSUE THREAD

**Issue by rohitnick** [JustinLove/autoscaler#65]
Getting the below error because of Heroku's shutting down Legacy Platform API (v2)

`Heroku::API::Errors::ErrorWithResponse: Expected(200) <=> Actual(410 Gone)`
`body: "{\"id\":\"gone\",\"error\":\"This version of the API has been Sunset.\\nPlease see https://devcenter.heroku.com/changelog-items/1147 for more information.\\n\"}">`

**Comment by crm114** [comment]
@rohitnick 
Change your initializer (config/initializers/sidekiq.rb) to this one which uses the new api:

https://github.com/JustinLove/autoscaler/blob/master/examples/simple.rb

Also, do heroku config:set HEROKU_ACCESS_TOKEN=your-api-key*

* Do heroku config and look for HEROKU_API_KEY

**Comment by ivanzotov** [comment]
@crm114 saved my life, thank you ))

**Comment by JustinLove** [comment]
0.14 adds a warning when creating HerokuScaler. The class will be removed in a future release.
