### ISSUE TITLE
Rename ENV vars

### ISSUE THREAD

**Issue by espen** [JustinLove/autoscaler#66]
The new Heroku-16 stack reserves HEROKU_* ENV vars for Heroku. See https://devcenter.heroku.com/articles/heroku-16-stack#what-s-new

> The HEROKU_ namespace is reserved for config vars set by the Heroku platform in order to offer functionality. If you have created HEROKU_ config vars, we suggest you change them when upgrading to Heroku-16, in order to avoid config var conflicts.

**Comment by JustinLove** [comment]
Any preference for

AS_HEROKU_APP
AS_HEROKU_ACCESS_TOKEN

vs

AUTOSCALER_HEROKU_APP
AUTOSCALER_HEROKU_ACCESS_TOKEN

Last being more explicit, but a bit long.

**Comment by JustinLove** [comment]
Secondly, there might be a major release at some point to remove old api (#65) Would it ever make sense to remove the old variables a fallback option?

**Comment by espen** [comment]
I'm using AUTOSCALER_APP and AUTOSCALER_ACCESS_TOKEN.

I don't think the variable length is an issue. If Heroku has a max length it's quite long (considering it's a name). I think it's more important to show autoscaler in the name than Heroku though. So my vote would either be AUTOSCALER_HEROKU_APP or if a shorter version is preferred then AUTOSCALER_APP. But it's not really that important, the only key thing is to not have HEROKU_* for apps on the new stack.

* insert joke about two difficult things in computer science *

**Comment by JustinLove** [comment]
0.14 adds AUTOSCALER_ prefix, old form supported with warning.
