### ISSUE TITLE
Autoscaler is passaing Incorrect Authentication "type" param to platform-api

### ISSUE THREAD

**Issue by gedean** [JustinLove/autoscaler#67]
Hi,

I instantiate a new Autoscaler::HerokuPlatformScaler object like this: 
`as = Autoscaler::HerokuPlatformScaler.new type: 'worker', token: 'my-token', app: 'my-app-name'`

when I ivoke type method, I got a hash, instead of type "worker"
`as.type`
**output:** {:type=>"worker", :token=>"my-token", :app=>"my-app-name"}

This way, it is passing wrong arguments to *heroku_set_workers* method, and I got following error on production:

`"Scaling worker to 1" 
Excon::Error::Unauthorized: Expected([200, 201, 202, 204, 206, 304]) <=> Actual(401 Unauthorized) `

**My enviroment:**
**Ruby**: ruby 2.3.4p301
**Rails**: 3.2.22.5

**Comment by JustinLove** [comment]
HerokuPlatformScaler takes three positional arguments, all of which are optional. You appear to be passing a hash as the first argument.

Perhaps there should be a warning if the first argument is not a string (or sufficiently string-like)?

**Comment by gedean** [comment]
As I said, I got a lot of errors in production enviroment using the gem in default way (getting params from .ENV stored in heroku). I just used the gem passing params by hand in my developement environment just to debug It and understand the reason of the raising of Unauthorized error.

I just cut out the old fashion environment params names and it worked fine for me. Check it out:

https://github.com/gedean/autoscaler/blob/master/lib/autoscaler/heroku_platform_scaler.rb

I didn't made a pull request becouse I understand, as you said in the readme.md, you want keep retrocompatibility till the new version of the gem. So I did a fork of your repository and made the change who fix my specific problem.

**Comment by JustinLove** [comment]
The part where you got errors using .env seems to have been lost from your original report. I'd need complete reproduction steps to address that.

Otherwise, all I'm seeing is that you want to use a different interface than the one provided, and would rather fork the library than change your invocation.

**Comment by JustinLove** [comment]
HerokuPlatformScaler and Strategies updated to use named parameters in 1.0.0
